### ISSUE TITLE
Error due to different capitalization

### ISSUE THREAD

**Issue by Suhansanu** [IllinoisSocialMediaMacroscope/collectionScripts#2]
The keywords in the folder **networkAnalysis** uses, 'Author', 'Contents', etc. while the original data generates with keywords 'author', 'contents'.

Fixing the capitalization any place will fix the error. I prefer that keywords should be without caps, therefore the keywords in the folder **networkAnalysis** should be converted to 'author', 'contents', etc.

**Comment by npvance2Illinois** [comment]
Had to change CrimsonPosts keywords to caps as the bulk export from the Crimson website names them in caps and we want this script to be usable with both exporting options.
